#############################################################################
# Makefile for building: Capturer
# Generated by qmake (2.01a) (Qt 4.8.3) on: sáb mar 16 15:32:26 2013
# Project:  Capturer.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Capturer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lprotobuf -lopencv_core -lopencv_video -lopencv_imgproc -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		imageviewerwindow.cpp \
		image_thread.cpp \
		cvmatandqimage.cpp protocol.pb.cc \
		moc_imageviewerwindow.cpp \
		moc_image_thread.cpp
OBJECTS       = main.o \
		imageviewerwindow.o \
		image_thread.o \
		cvmatandqimage.o \
		protocol.pb.o \
		moc_imageviewerwindow.o \
		moc_image_thread.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		opencv.pri \
		QtOpenCV.pri \
		protobuf.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Capturer.pro
QMAKE_TARGET  = Capturer
DESTDIR       = 
TARGET        = Capturer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_imageviewerwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: Capturer.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		opencv.pri \
		QtOpenCV.pri \
		protobuf.pri \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Capturer.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
opencv.pri:
QtOpenCV.pri:
protobuf.pri:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Capturer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Capturer1.0.0 || $(MKDIR) .tmp/Capturer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Capturer1.0.0/ && $(COPY_FILE) --parents protocol.proto .tmp/Capturer1.0.0/ && $(COPY_FILE) --parents protocol.proto .tmp/Capturer1.0.0/ && $(COPY_FILE) --parents imageviewerwindow.h image_thread.h cvmatandqimage.h .tmp/Capturer1.0.0/ && $(COPY_FILE) --parents main.cpp imageviewerwindow.cpp image_thread.cpp cvmatandqimage.cpp .tmp/Capturer1.0.0/ && $(COPY_FILE) --parents imageviewerwindow.ui .tmp/Capturer1.0.0/ && (cd `dirname .tmp/Capturer1.0.0` && $(TAR) Capturer1.0.0.tar Capturer1.0.0 && $(COMPRESS) Capturer1.0.0.tar) && $(MOVE) `dirname .tmp/Capturer1.0.0`/Capturer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Capturer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_protobuf_decl_make_all: protocol.pb.h
compiler_protobuf_decl_clean:
	-$(DEL_FILE) protocol.pb.h
protocol.pb.h: protocol.proto
	protoc --cpp_out=. --proto_path=. protocol.proto

compiler_protobuf_impl_make_all: protocol.pb.cc
compiler_protobuf_impl_clean:
	-$(DEL_FILE) protocol.pb.cc
protocol.pb.cc: protocol.proto \
		protocol.pb.h
	


compiler_moc_header_make_all: moc_imageviewerwindow.cpp moc_image_thread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_imageviewerwindow.cpp moc_image_thread.cpp
moc_imageviewerwindow.cpp: image_thread.h \
		cvmatandqimage.h \
		imageviewerwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) imageviewerwindow.h -o moc_imageviewerwindow.cpp

moc_image_thread.cpp: cvmatandqimage.h \
		image_thread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) image_thread.h -o moc_image_thread.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_imageviewerwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_imageviewerwindow.h
ui_imageviewerwindow.h: imageviewerwindow.ui
	/usr/bin/uic-qt4 imageviewerwindow.ui -o ui_imageviewerwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_protobuf_decl_clean compiler_protobuf_impl_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp imageviewerwindow.h \
		image_thread.h \
		cvmatandqimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

imageviewerwindow.o: imageviewerwindow.cpp imageviewerwindow.h \
		image_thread.h \
		cvmatandqimage.h \
		ui_imageviewerwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageviewerwindow.o imageviewerwindow.cpp

image_thread.o: image_thread.cpp image_thread.h \
		cvmatandqimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o image_thread.o image_thread.cpp

cvmatandqimage.o: cvmatandqimage.cpp cvmatandqimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cvmatandqimage.o cvmatandqimage.cpp

protocol.pb.o: protocol.pb.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o protocol.pb.o protocol.pb.cc

moc_imageviewerwindow.o: moc_imageviewerwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imageviewerwindow.o moc_imageviewerwindow.cpp

moc_image_thread.o: moc_image_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_image_thread.o moc_image_thread.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

